import { Unit } from './types'

export const units: Unit[] = [
  // ─── BASICS ───────────────────────────────────────────────────────────────
  {
    id: 'basics-greetings',
    level: 'basics',
    title: 'Greetings',
    description: 'Say hello, thank you, and goodbye',
    imageQuery: 'people greeting china',
    clusters: [
      {
        id: 'basics-greetings-1',
        title: 'Hello & Thank You',
        scenarioDescription: 'A shopkeeper greets you as you enter their store',
        conversationContext:
          'You are playing a friendly shopkeeper in China. The learner is a tourist entering your shop. Greet them warmly, exchange pleasantries, and thank them for visiting.',
        words: [
          {
            character: '你好',
            pinyin: 'nǐ hǎo',
            meaning: 'Hello',
            phoneticGuide: 'knee HOW',
            toneNote: '"ni" falls then rises, "hao" falls then rises',
            imageQuery: 'friendly greeting handshake',
          },
          {
            character: '谢谢',
            pinyin: 'xiè xie',
            meaning: 'Thank you',
            phoneticGuide: 'sheh sheh',
            toneNote: '"xie" falls sharply, second "xie" is neutral/light',
            imageQuery: 'gratitude thank you gesture',
          },
          {
            character: '不客气',
            pinyin: 'bú kè qi',
            meaning: "You're welcome",
            phoneticGuide: 'boo kuh chee',
            toneNote: '"bu" rises, "ke" falls, "qi" is neutral',
            imageQuery: 'welcoming smile',
          },
        ],
        phrase: {
          chinese: '你好！谢谢你。',
          pinyin: 'Nǐ hǎo! Xiè xie nǐ.',
          meaning: 'Hello! Thank you.',
          breakdown: [
            { chinese: '你好', pinyin: 'nǐ hǎo', meaning: 'Hello' },
            { chinese: '谢谢', pinyin: 'xiè xie', meaning: 'Thank you' },
            { chinese: '你', pinyin: 'nǐ', meaning: 'you' },
          ],
        },
      },
      {
        id: 'basics-greetings-2',
        title: 'Goodbye & Sorry',
        scenarioDescription: 'You accidentally bump into someone on a busy street',
        conversationContext:
          'You are a passerby on a busy street in Beijing. The learner accidentally bumps into you. React naturally, accept their apology, and say goodbye politely.',
        words: [
          {
            character: '再见',
            pinyin: 'zài jiàn',
            meaning: 'Goodbye',
            phoneticGuide: 'dzai JYEN',
            toneNote: '"zai" falls, "jian" falls',
            imageQuery: 'waving goodbye',
          },
          {
            character: '对不起',
            pinyin: 'duì bu qǐ',
            meaning: 'Sorry / Excuse me',
            phoneticGuide: 'dway boo CHEE',
            toneNote: '"dui" falls, "bu" is neutral, "qi" falls then rises',
            imageQuery: 'apology sorry expression',
          },
          {
            character: '没关系',
            pinyin: 'méi guān xi',
            meaning: "It's okay / No problem",
            phoneticGuide: 'may gwahn SHEE',
            toneNote: '"mei" rises, "guan" is flat, "xi" is neutral',
            imageQuery: 'reassuring gesture ok',
          },
        ],
        phrase: {
          chinese: '对不起！没关系，再见。',
          pinyin: 'Duì bu qǐ! Méi guān xi, zài jiàn.',
          meaning: 'Sorry! No problem, goodbye.',
          breakdown: [
            { chinese: '对不起', pinyin: 'duì bu qǐ', meaning: 'Sorry' },
            { chinese: '没关系', pinyin: 'méi guān xi', meaning: 'No problem' },
            { chinese: '再见', pinyin: 'zài jiàn', meaning: 'Goodbye' },
          ],
        },
      },
      {
        id: 'basics-greetings-3',
        title: 'Morning & Evening',
        scenarioDescription: 'You run into your neighbour on the way out in the morning',
        conversationContext:
          'You are a friendly neighbour in a residential block in China. The learner passes you in the morning. Exchange time-of-day greetings and ask how they are doing.',
        words: [
          {
            character: '早上好',
            pinyin: 'zǎoshang hǎo',
            meaning: 'Good morning',
            phoneticGuide: 'dzow-shahng HOW',
            toneNote: '"zao" falls-rises, "shang" rises, "hao" falls-rises',
            imageQuery: 'morning sunrise breakfast',
          },
          {
            character: '晚上好',
            pinyin: 'wǎnshang hǎo',
            meaning: 'Good evening',
            phoneticGuide: 'wahn-shahng HOW',
            toneNote: '"wan" falls-rises, "shang" rises, "hao" falls-rises',
            imageQuery: 'evening sunset city lights',
          },
          {
            character: '怎么样',
            pinyin: 'zěnmeyàng',
            meaning: 'How is it going?',
            phoneticGuide: 'dzen-muh-YAHNG',
            toneNote: '"zen" falls-rises, "me" neutral, "yang" falls',
            imageQuery: 'casual conversation friends',
          },
        ],
        phrase: {
          chinese: '早上好！今天怎么样？',
          pinyin: 'Zǎoshang hǎo! Jīntiān zěnmeyàng?',
          meaning: 'Good morning! How are things today?',
          breakdown: [
            { chinese: '早上好', pinyin: 'zǎoshang hǎo', meaning: 'Good morning' },
            { chinese: '今天', pinyin: 'jīntiān', meaning: 'today' },
            { chinese: '怎么样', pinyin: 'zěnmeyàng', meaning: 'how is it going?' },
          ],
        },
      },
    ],
  },

  {
    id: 'basics-introductions',
    level: 'basics',
    title: 'Introductions',
    description: 'Tell people your name and ask theirs',
    imageQuery: 'introduction meeting people',
    clusters: [
      {
        id: 'basics-intro-1',
        title: 'What is Your Name?',
        scenarioDescription: 'You are meeting a new colleague at a work event',
        conversationContext:
          'You are at a networking event in Shanghai. Introduce yourself to the learner and ask their name. Be warm and professional.',
        words: [
          {
            character: '我叫',
            pinyin: 'wǒ jiào',
            meaning: 'My name is / I am called',
            phoneticGuide: 'waw JYOW',
            toneNote: '"wo" falls then rises, "jiao" falls',
            imageQuery: 'pointing to self introduction',
          },
          {
            character: '你叫什么名字',
            pinyin: 'nǐ jiào shénme míngzi',
            meaning: 'What is your name?',
            phoneticGuide: 'knee jyow SHEN-muh MING-dzuh',
            toneNote: '"shen" rises, "me" neutral, "ming" rises, "zi" neutral',
            imageQuery: 'asking question curious',
          },
          {
            character: '很高兴认识你',
            pinyin: 'hěn gāo xìng rèn shi nǐ',
            meaning: 'Nice to meet you',
            phoneticGuide: 'hun GOW shing REN shrr nee',
            toneNote: '"hen" falls-rises, "gao" flat, "xing" falls',
            imageQuery: 'nice to meet you handshake smile',
          },
        ],
        phrase: {
          chinese: '你好！我叫___。你叫什么名字？',
          pinyin: 'Nǐ hǎo! Wǒ jiào ___. Nǐ jiào shénme míngzi?',
          meaning: 'Hello! My name is ___. What is your name?',
          breakdown: [
            { chinese: '你好', pinyin: 'nǐ hǎo', meaning: 'Hello' },
            { chinese: '我叫', pinyin: 'wǒ jiào', meaning: 'My name is' },
            { chinese: '你叫什么名字', pinyin: 'nǐ jiào shénme míngzi', meaning: 'What is your name?' },
          ],
        },
      },
      {
        id: 'basics-intro-2',
        title: 'Where Are You From?',
        scenarioDescription: 'A new acquaintance asks about your nationality',
        conversationContext:
          'You are a curious local at a café in Chengdu. The learner is a foreigner. Ask where they are from and tell them about yourself.',
        words: [
          {
            character: '你从哪里来',
            pinyin: 'nǐ cóng nǎlǐ lái',
            meaning: 'Where are you from?',
            phoneticGuide: 'knee TSONG NAH-lee LYE',
            toneNote: '"cong" rising, "na" falls-rises, "lai" rising',
            imageQuery: 'globe world map travel',
          },
          {
            character: '英国',
            pinyin: 'Yīngguó',
            meaning: 'United Kingdom',
            phoneticGuide: 'ying GWAW',
            toneNote: '"ying" flat, "guo" rising',
            imageQuery: 'london england uk flag',
          },
          {
            character: '美国',
            pinyin: 'Měiguó',
            meaning: 'United States',
            phoneticGuide: 'may GWAW',
            toneNote: '"mei" falls-rises, "guo" rising',
            imageQuery: 'new york usa america',
          },
        ],
        phrase: {
          chinese: '你从哪里来？我从英国来。',
          pinyin: 'Nǐ cóng nǎlǐ lái? Wǒ cóng Yīngguó lái.',
          meaning: "Where are you from? I'm from the UK.",
          breakdown: [
            { chinese: '你从哪里来', pinyin: 'nǐ cóng nǎlǐ lái', meaning: 'Where are you from?' },
            { chinese: '我从', pinyin: 'wǒ cóng', meaning: 'I from' },
            { chinese: '英国', pinyin: 'Yīngguó', meaning: 'UK' },
            { chinese: '来', pinyin: 'lái', meaning: 'come' },
          ],
        },
      },
      {
        id: 'basics-intro-3',
        title: 'Age & Occupation',
        scenarioDescription: 'Getting to know a new friend at a language exchange',
        conversationContext:
          'You are a Chinese student at a language exchange meetup. Ask the learner their age and what they do for work. Share your own details too.',
        words: [
          {
            character: '你多大',
            pinyin: 'nǐ duō dà',
            meaning: 'How old are you?',
            phoneticGuide: 'knee dwaw DAH',
            toneNote: '"duo" flat, "da" falls',
            imageQuery: 'birthday candles age celebration',
          },
          {
            character: '岁',
            pinyin: 'suì',
            meaning: 'Years old',
            phoneticGuide: 'sway',
            toneNote: 'falls sharply',
            imageQuery: 'number age years',
          },
          {
            character: '工作',
            pinyin: 'gōngzuò',
            meaning: 'Work / Job',
            phoneticGuide: 'gong DZWAW',
            toneNote: '"gong" flat, "zuo" falls',
            imageQuery: 'office work professional',
          },
        ],
        phrase: {
          chinese: '你多大？你做什么工作？',
          pinyin: 'Nǐ duō dà? Nǐ zuò shénme gōngzuò?',
          meaning: 'How old are you? What do you do for work?',
          breakdown: [
            { chinese: '你多大', pinyin: 'nǐ duō dà', meaning: 'How old are you?' },
            { chinese: '你做什么', pinyin: 'nǐ zuò shénme', meaning: 'What do you do?' },
            { chinese: '工作', pinyin: 'gōngzuò', meaning: 'work/job' },
          ],
        },
      },
    ],
  },

  {
    id: 'basics-numbers',
    level: 'basics',
    title: 'Numbers & Time',
    description: 'Count, tell the time, and talk about days',
    imageQuery: 'numbers counting china',
    clusters: [
      {
        id: 'basics-numbers-1',
        title: 'One to Five',
        scenarioDescription: 'You are ordering dim sum and need to say how many you want',
        conversationContext:
          'You are a dim sum server. Ask the learner how many of each dish they would like and practice counting together.',
        words: [
          {
            character: '一二三四五',
            pinyin: 'yī èr sān sì wǔ',
            meaning: 'One two three four five',
            phoneticGuide: 'ee AR sahn srr WOO',
            toneNote: '"yi" flat, "er" rising, "san" flat, "si" falling, "wu" falling-rising',
            imageQuery: 'counting fingers hand',
          },
          {
            character: '一',
            pinyin: 'yī',
            meaning: 'One',
            phoneticGuide: 'ee',
            toneNote: 'flat high tone — like a long "ee"',
            imageQuery: 'number one single',
          },
          {
            character: '两',
            pinyin: 'liǎng',
            meaning: 'Two (for counting things)',
            phoneticGuide: 'lyahng',
            toneNote: 'falls then rises, like a question in English',
            imageQuery: 'two items pair',
          },
        ],
        phrase: {
          chinese: '我要三个，谢谢。',
          pinyin: 'Wǒ yào sān gè, xiè xie.',
          meaning: 'I want three, thank you.',
          breakdown: [
            { chinese: '我要', pinyin: 'wǒ yào', meaning: 'I want' },
            { chinese: '三', pinyin: 'sān', meaning: 'three' },
            { chinese: '个', pinyin: 'gè', meaning: '(measure word)' },
          ],
        },
      },
      {
        id: 'basics-numbers-2',
        title: 'Six to Ten',
        scenarioDescription: 'You are at a market negotiating how many items to buy',
        conversationContext:
          'You are a market vendor. Practice numbers 6-10 with the learner as they buy fruit from your stall.',
        words: [
          {
            character: '六',
            pinyin: 'liù',
            meaning: 'Six',
            phoneticGuide: 'lyoh',
            toneNote: 'falls sharply',
            imageQuery: 'six fruit market',
          },
          {
            character: '七',
            pinyin: 'qī',
            meaning: 'Seven',
            phoneticGuide: 'chee',
            toneNote: 'flat high tone',
            imageQuery: 'seven items',
          },
          {
            character: '十',
            pinyin: 'shí',
            meaning: 'Ten',
            phoneticGuide: 'shrr',
            toneNote: 'rising tone',
            imageQuery: 'ten complete set',
          },
        ],
        phrase: {
          chinese: '我要八个苹果，多少钱？',
          pinyin: 'Wǒ yào bā gè píngguǒ, duōshao qián?',
          meaning: 'I want eight apples, how much?',
          breakdown: [
            { chinese: '我要', pinyin: 'wǒ yào', meaning: 'I want' },
            { chinese: '八', pinyin: 'bā', meaning: 'eight' },
            { chinese: '个', pinyin: 'gè', meaning: '(measure word)' },
            { chinese: '苹果', pinyin: 'píngguǒ', meaning: 'apple' },
            { chinese: '多少钱', pinyin: 'duōshao qián', meaning: 'how much?' },
          ],
        },
      },
      {
        id: 'basics-numbers-3',
        title: 'Telling the Time',
        scenarioDescription: 'You need to know what time it is to catch your train',
        conversationContext:
          'You are a commuter at a train station in China. The learner asks you for the time. Help them practise asking and understanding times.',
        words: [
          {
            character: '几点',
            pinyin: 'jǐ diǎn',
            meaning: "What time / how many o'clock",
            phoneticGuide: 'jee DYEN',
            toneNote: '"ji" falls-rises, "dian" falls-rises',
            imageQuery: 'clock time watch',
          },
          {
            character: '现在',
            pinyin: 'xiànzài',
            meaning: 'Now / right now',
            phoneticGuide: 'shyen DZAI',
            toneNote: '"xian" falls, "zai" falls',
            imageQuery: 'present moment now',
          },
          {
            character: '半',
            pinyin: 'bàn',
            meaning: 'Half (past)',
            phoneticGuide: 'bahn',
            toneNote: 'falls sharply',
            imageQuery: 'half clock thirty minutes',
          },
        ],
        phrase: {
          chinese: '现在几点？三点半。',
          pinyin: 'Xiànzài jǐ diǎn? Sān diǎn bàn.',
          meaning: 'What time is it now? Half past three.',
          breakdown: [
            { chinese: '现在', pinyin: 'xiànzài', meaning: 'now' },
            { chinese: '几点', pinyin: 'jǐ diǎn', meaning: 'what time?' },
            { chinese: '三点', pinyin: 'sān diǎn', meaning: "three o'clock" },
            { chinese: '半', pinyin: 'bàn', meaning: 'half' },
          ],
        },
      },
      {
        id: 'basics-numbers-4',
        title: 'Days of the Week',
        scenarioDescription: 'Planning weekend activities with a friend',
        conversationContext:
          'You are a friend of the learner. Discuss what day it is and plan something fun for the weekend.',
        words: [
          {
            character: '今天',
            pinyin: 'jīntiān',
            meaning: 'Today',
            phoneticGuide: 'jin TYEN',
            toneNote: '"jin" flat, "tian" flat',
            imageQuery: 'today calendar date',
          },
          {
            character: '星期',
            pinyin: 'xīngqī',
            meaning: 'Day of the week',
            phoneticGuide: 'shing CHEE',
            toneNote: '"xing" flat, "qi" flat',
            imageQuery: 'weekly calendar schedule',
          },
          {
            character: '周末',
            pinyin: 'zhōumò',
            meaning: 'Weekend',
            phoneticGuide: 'joh MOH',
            toneNote: '"zhou" flat, "mo" falls',
            imageQuery: 'weekend relaxation leisure',
          },
        ],
        phrase: {
          chinese: '今天星期几？今天星期五，明天是周末。',
          pinyin: 'Jīntiān xīngqī jǐ? Jīntiān xīngqīwǔ, míngtiān shì zhōumò.',
          meaning: 'What day is today? Today is Friday, tomorrow is the weekend.',
          breakdown: [
            { chinese: '今天', pinyin: 'jīntiān', meaning: 'today' },
            { chinese: '星期几', pinyin: 'xīngqī jǐ', meaning: 'which day of the week?' },
            { chinese: '星期五', pinyin: 'xīngqīwǔ', meaning: 'Friday' },
            { chinese: '周末', pinyin: 'zhōumò', meaning: 'weekend' },
          ],
        },
      },
    ],
  },

  {
    id: 'basics-daily',
    level: 'basics',
    title: 'Daily Life',
    description: 'Food, places, and asking for help',
    imageQuery: 'everyday life china street',
    clusters: [
      {
        id: 'basics-daily-1',
        title: 'Food & Drink',
        scenarioDescription: 'You are a guest at a Chinese home and feel hungry and thirsty',
        conversationContext:
          'You are a Chinese host welcoming a foreign visitor into your home. Offer them food and drink and make sure they are comfortable.',
        words: [
          {
            character: '吃',
            pinyin: 'chī',
            meaning: 'Eat',
            phoneticGuide: 'chrr',
            toneNote: 'flat high tone',
            imageQuery: 'eating food chopsticks',
          },
          {
            character: '喝',
            pinyin: 'hē',
            meaning: 'Drink',
            phoneticGuide: 'huh',
            toneNote: 'flat high tone',
            imageQuery: 'drinking tea cup',
          },
          {
            character: '水',
            pinyin: 'shuǐ',
            meaning: 'Water',
            phoneticGuide: 'shway',
            toneNote: 'falls then rises',
            imageQuery: 'glass of water clear',
          },
        ],
        phrase: {
          chinese: '我渴了，你有水吗？',
          pinyin: 'Wǒ kě le, nǐ yǒu shuǐ ma?',
          meaning: "I'm thirsty, do you have water?",
          breakdown: [
            { chinese: '我渴了', pinyin: 'wǒ kě le', meaning: 'I am thirsty' },
            { chinese: '你有', pinyin: 'nǐ yǒu', meaning: 'do you have' },
            { chinese: '水', pinyin: 'shuǐ', meaning: 'water' },
            { chinese: '吗', pinyin: 'ma', meaning: '(question particle)' },
          ],
        },
      },
      {
        id: 'basics-daily-2',
        title: 'Finding Places',
        scenarioDescription: 'You need to find a supermarket in an unfamiliar neighbourhood',
        conversationContext:
          'You are a friendly local in a Chinese city. A tourist is asking you where to find common places nearby. Help them with simple directions.',
        words: [
          {
            character: '银行',
            pinyin: 'yínháng',
            meaning: 'Bank',
            phoneticGuide: 'yin HAHNG',
            toneNote: '"yin" rising, "hang" falls',
            imageQuery: 'bank building financial',
          },
          {
            character: '超市',
            pinyin: 'chāoshì',
            meaning: 'Supermarket',
            phoneticGuide: 'chow SHRR',
            toneNote: '"chao" flat, "shi" falls',
            imageQuery: 'supermarket grocery store aisle',
          },
          {
            character: '附近',
            pinyin: 'fùjìn',
            meaning: 'Nearby / in the vicinity',
            phoneticGuide: 'foo JIN',
            toneNote: '"fu" falls, "jin" falls',
            imageQuery: 'map nearby location',
          },
        ],
        phrase: {
          chinese: '请问，附近有超市吗？',
          pinyin: 'Qǐngwèn, fùjìn yǒu chāoshì ma?',
          meaning: 'Excuse me, is there a supermarket nearby?',
          breakdown: [
            { chinese: '请问', pinyin: 'qǐngwèn', meaning: 'excuse me / may I ask' },
            { chinese: '附近', pinyin: 'fùjìn', meaning: 'nearby' },
            { chinese: '有', pinyin: 'yǒu', meaning: 'there is / have' },
            { chinese: '超市吗', pinyin: 'chāoshì ma', meaning: 'supermarket?' },
          ],
        },
      },
      {
        id: 'basics-daily-3',
        title: 'Asking for Help',
        scenarioDescription: 'You did not understand what someone said and need them to repeat',
        conversationContext:
          'You are a patient Chinese speaker chatting with the learner. They are struggling to follow. Encourage them to ask you to slow down or repeat yourself.',
        words: [
          {
            character: '不明白',
            pinyin: 'bù míngbai',
            meaning: "Don't understand",
            phoneticGuide: 'boo MING-bye',
            toneNote: '"bu" falls, "ming" rising, "bai" neutral',
            imageQuery: 'confused puzzled expression',
          },
          {
            character: '请再说一遍',
            pinyin: 'qǐng zài shuō yī biàn',
            meaning: 'Please say it again',
            phoneticGuide: 'ching dzai SHWAW ee BYEN',
            toneNote: '"qing" falls-rises, "zai" falls, "shuo" falls-rises, "bian" falls',
            imageQuery: 'repeat listening ears',
          },
          {
            character: '慢一点',
            pinyin: 'màn yīdiǎn',
            meaning: 'A bit slower',
            phoneticGuide: 'mahn ee-DYEN',
            toneNote: '"man" falls, "yi" flat, "dian" falls-rises',
            imageQuery: 'slow pace gentle',
          },
        ],
        phrase: {
          chinese: '对不起，我不明白。请再说一遍，慢一点。',
          pinyin: 'Duì bu qǐ, wǒ bù míngbai. Qǐng zài shuō yī biàn, màn yīdiǎn.',
          meaning: "Sorry, I don't understand. Please say it again, a bit slower.",
          breakdown: [
            { chinese: '我不明白', pinyin: 'wǒ bù míngbai', meaning: "I don't understand" },
            { chinese: '请再说一遍', pinyin: 'qǐng zài shuō yī biàn', meaning: 'please say again' },
            { chinese: '慢一点', pinyin: 'màn yīdiǎn', meaning: 'a bit slower' },
          ],
        },
      },
    ],
  },

  // ─── TRAVEL ───────────────────────────────────────────────────────────────
  {
    id: 'travel-restaurant',
    level: 'travel',
    title: 'At a Restaurant',
    description: 'Order food, ask about dishes, and pay the bill',
    imageQuery: 'chinese restaurant food dining',
    clusters: [
      {
        id: 'travel-restaurant-1',
        title: 'Ordering Food',
        scenarioDescription: 'You sit down at a restaurant and want to order',
        conversationContext:
          'You are a waiter at a traditional Chinese restaurant. Welcome the learner, offer a menu, take their order, and answer questions about the food.',
        words: [
          {
            character: '菜单',
            pinyin: 'càidān',
            meaning: 'Menu',
            phoneticGuide: 'tsai DAHN',
            toneNote: '"cai" falls, "dan" flat',
            imageQuery: 'restaurant menu chinese',
          },
          {
            character: '好吃',
            pinyin: 'hǎo chī',
            meaning: 'Delicious',
            phoneticGuide: 'how CHRR',
            toneNote: '"hao" falls-rises, "chi" flat',
            imageQuery: 'delicious food eating',
          },
          {
            character: '我要这个',
            pinyin: 'wǒ yào zhè gè',
            meaning: 'I want this one',
            phoneticGuide: 'waw YOW juh guh',
            toneNote: '"wo" falls-rises, "yao" falls, "zhe" falls, "ge" neutral',
            imageQuery: 'pointing at menu ordering',
          },
        ],
        phrase: {
          chinese: '请给我菜单。我要这个，谢谢。',
          pinyin: 'Qǐng gěi wǒ càidān. Wǒ yào zhè gè, xiè xie.',
          meaning: 'Please give me the menu. I want this one, thank you.',
          breakdown: [
            { chinese: '请', pinyin: 'qǐng', meaning: 'please' },
            { chinese: '给我', pinyin: 'gěi wǒ', meaning: 'give me' },
            { chinese: '菜单', pinyin: 'càidān', meaning: 'menu' },
            { chinese: '我要这个', pinyin: 'wǒ yào zhè gè', meaning: 'I want this one' },
          ],
        },
      },
      {
        id: 'travel-restaurant-2',
        title: 'Paying the Bill',
        scenarioDescription: 'You have finished your meal and want to pay',
        conversationContext:
          'You are a waiter at a restaurant. The learner wants to pay. Help them ask for the bill and tell them the price.',
        words: [
          {
            character: '多少钱',
            pinyin: 'duōshao qián',
            meaning: 'How much money?',
            phoneticGuide: 'dwaw SHAO chyen',
            toneNote: '"duo" flat, "shao" rising, "qian" rising',
            imageQuery: 'paying money bill',
          },
          {
            character: '买单',
            pinyin: 'mǎi dān',
            meaning: 'The bill please',
            phoneticGuide: 'my DAHN',
            toneNote: '"mai" falls-rises, "dan" flat',
            imageQuery: 'restaurant bill receipt',
          },
          {
            character: '刷卡',
            pinyin: 'shuā kǎ',
            meaning: 'Pay by card',
            phoneticGuide: 'shwah KAH',
            toneNote: '"shua" flat, "ka" falls-rises',
            imageQuery: 'credit card payment',
          },
        ],
        phrase: {
          chinese: '买单！多少钱？可以刷卡吗？',
          pinyin: 'Mǎi dān! Duōshao qián? Kěyǐ shuā kǎ ma?',
          meaning: 'The bill please! How much? Can I pay by card?',
          breakdown: [
            { chinese: '买单', pinyin: 'mǎi dān', meaning: 'bill please' },
            { chinese: '多少钱', pinyin: 'duōshao qián', meaning: 'how much?' },
            { chinese: '可以', pinyin: 'kěyǐ', meaning: 'can / is it okay' },
            { chinese: '刷卡', pinyin: 'shuā kǎ', meaning: 'pay by card' },
            { chinese: '吗', pinyin: 'ma', meaning: '(question particle)' },
          ],
        },
      },
      {
        id: 'travel-restaurant-3',
        title: 'Dietary Preferences',
        scenarioDescription: 'You need to tell the waiter about your food restrictions',
        conversationContext:
          'You are a waiter at a Chinese restaurant. The learner has a food allergy and does not eat spicy food. Help them communicate their dietary needs.',
        words: [
          {
            character: '辣',
            pinyin: 'là',
            meaning: 'Spicy',
            phoneticGuide: 'lah',
            toneNote: 'falls sharply',
            imageQuery: 'spicy chili peppers red hot',
          },
          {
            character: '过敏',
            pinyin: 'guòmǐn',
            meaning: 'Allergy',
            phoneticGuide: 'gwaw MIN',
            toneNote: '"guo" falls, "min" falls-rises',
            imageQuery: 'allergy food warning',
          },
          {
            character: '素食',
            pinyin: 'sùshí',
            meaning: 'Vegetarian',
            phoneticGuide: 'soo SHRR',
            toneNote: '"su" falls, "shi" rising',
            imageQuery: 'vegetarian vegetables healthy',
          },
        ],
        phrase: {
          chinese: '我不吃辣，我对花生过敏。',
          pinyin: 'Wǒ bù chī là, wǒ duì huāshēng guòmǐn.',
          meaning: "I don't eat spicy food, I'm allergic to peanuts.",
          breakdown: [
            { chinese: '我不吃辣', pinyin: 'wǒ bù chī là', meaning: "I don't eat spicy" },
            { chinese: '我对', pinyin: 'wǒ duì', meaning: 'I am (allergic) to' },
            { chinese: '花生', pinyin: 'huāshēng', meaning: 'peanuts' },
            { chinese: '过敏', pinyin: 'guòmǐn', meaning: 'allergic' },
          ],
        },
      },
    ],
  },

  {
    id: 'travel-directions',
    level: 'travel',
    title: 'Getting Around',
    description: 'Ask for directions and use transport',
    imageQuery: 'beijing street navigation china',
    clusters: [
      {
        id: 'travel-directions-1',
        title: 'Basic Directions',
        scenarioDescription: 'You are lost and need to find the subway station',
        conversationContext:
          'You are a helpful local on the street in Beijing. The learner is lost and trying to find the subway. Give them simple directions.',
        words: [
          {
            character: '左',
            pinyin: 'zuǒ',
            meaning: 'Left',
            phoneticGuide: 'dzwaw',
            toneNote: 'falls then rises',
            imageQuery: 'direction left arrow',
          },
          {
            character: '右',
            pinyin: 'yòu',
            meaning: 'Right',
            phoneticGuide: 'yo',
            toneNote: 'falls sharply',
            imageQuery: 'direction right arrow',
          },
          {
            character: '地铁站',
            pinyin: 'dìtiě zhàn',
            meaning: 'Subway / metro station',
            phoneticGuide: 'dee TYEH jahn',
            toneNote: '"di" falls, "tie" falls-rises, "zhan" falls',
            imageQuery: 'beijing subway metro station',
          },
        ],
        phrase: {
          chinese: '请问，地铁站在哪里？',
          pinyin: 'Qǐngwèn, dìtiě zhàn zài nǎlǐ?',
          meaning: 'Excuse me, where is the subway station?',
          breakdown: [
            { chinese: '请问', pinyin: 'qǐngwèn', meaning: 'excuse me / may I ask' },
            { chinese: '地铁站', pinyin: 'dìtiě zhàn', meaning: 'subway station' },
            { chinese: '在哪里', pinyin: 'zài nǎlǐ', meaning: 'where is it?' },
          ],
        },
      },
      {
        id: 'travel-directions-2',
        title: 'Taking a Taxi',
        scenarioDescription: 'You hail a cab and need to tell the driver where to go',
        conversationContext:
          'You are a taxi driver in Beijing. The learner has just got in and wants to go to a famous landmark. Ask them where they are going and make friendly small talk.',
        words: [
          {
            character: '出租车',
            pinyin: 'chūzūchē',
            meaning: 'Taxi',
            phoneticGuide: 'choo-dzoo-CHUH',
            toneNote: '"chu" flat, "zu" flat, "che" flat',
            imageQuery: 'taxi cab yellow street',
          },
          {
            character: '去',
            pinyin: 'qù',
            meaning: 'Go to',
            phoneticGuide: 'chew',
            toneNote: 'falls sharply',
            imageQuery: 'direction destination arrow',
          },
          {
            character: '多远',
            pinyin: 'duō yuǎn',
            meaning: 'How far?',
            phoneticGuide: 'dwaw YWEN',
            toneNote: '"duo" flat, "yuan" falls-rises',
            imageQuery: 'distance road long journey',
          },
        ],
        phrase: {
          chinese: '我要去故宫，大概多远？',
          pinyin: 'Wǒ yào qù Gùgōng, dàgài duō yuǎn?',
          meaning: 'I want to go to the Forbidden City, about how far?',
          breakdown: [
            { chinese: '我要去', pinyin: 'wǒ yào qù', meaning: 'I want to go to' },
            { chinese: '故宫', pinyin: 'Gùgōng', meaning: 'Forbidden City' },
            { chinese: '大概', pinyin: 'dàgài', meaning: 'approximately' },
            { chinese: '多远', pinyin: 'duō yuǎn', meaning: 'how far?' },
          ],
        },
      },
      {
        id: 'travel-directions-3',
        title: 'Public Transport',
        scenarioDescription: 'You need to navigate the subway to reach a tourist site',
        conversationContext:
          'You are a subway station attendant in Shanghai. The learner is trying to figure out how to get to a famous destination. Help them understand which line to take and whether they need to transfer.',
        words: [
          {
            character: '换乘',
            pinyin: 'huànchéng',
            meaning: 'Transfer / change lines',
            phoneticGuide: 'hwahn CHUNG',
            toneNote: '"huan" falls, "cheng" rising',
            imageQuery: 'subway transfer connection metro',
          },
          {
            character: '哪一站',
            pinyin: 'nǎ yī zhàn',
            meaning: 'Which stop?',
            phoneticGuide: 'nah ee JAHN',
            toneNote: '"na" falls-rises, "yi" flat, "zhan" falls',
            imageQuery: 'train stop station sign',
          },
          {
            character: '下车',
            pinyin: 'xià chē',
            meaning: 'Get off (the vehicle)',
            phoneticGuide: 'shyah CHUH',
            toneNote: '"xia" falls, "che" flat',
            imageQuery: 'exit bus train doors',
          },
        ],
        phrase: {
          chinese: '请问，去天安门要换乘吗？在哪一站下车？',
          pinyin: 'Qǐngwèn, qù Tiān\'ānmén yào huànchéng ma? Zài nǎ yī zhàn xià chē?',
          meaning: 'Excuse me, do I need to transfer to get to Tiananmen? Which stop do I get off at?',
          breakdown: [
            { chinese: '去天安门', pinyin: 'qù Tiān\'ānmén', meaning: 'to Tiananmen' },
            { chinese: '要换乘吗', pinyin: 'yào huànchéng ma', meaning: 'need to transfer?' },
            { chinese: '哪一站', pinyin: 'nǎ yī zhàn', meaning: 'which stop' },
            { chinese: '下车', pinyin: 'xià chē', meaning: 'get off' },
          ],
        },
      },
    ],
  },

  {
    id: 'travel-shopping',
    level: 'travel',
    title: 'Shopping',
    description: 'Browse, ask prices, bargain, and buy',
    imageQuery: 'china market shopping street',
    clusters: [
      {
        id: 'travel-shopping-1',
        title: 'Asking Prices & Bargaining',
        scenarioDescription: 'You are at a market stall looking at souvenirs',
        conversationContext:
          'You are a market vendor selling souvenirs in Shanghai. The learner wants to buy something but thinks it is too expensive. Help them practice bargaining.',
        words: [
          {
            character: '贵',
            pinyin: 'guì',
            meaning: 'Expensive',
            phoneticGuide: 'gway',
            toneNote: 'falls sharply',
            imageQuery: 'expensive luxury price tag',
          },
          {
            character: '便宜',
            pinyin: 'piányí',
            meaning: 'Cheap / inexpensive',
            phoneticGuide: 'pyen EE',
            toneNote: '"pian" rising, "yi" rising',
            imageQuery: 'cheap bargain sale market',
          },
          {
            character: '能便宜点吗',
            pinyin: 'néng piányí diǎn ma',
            meaning: 'Can you make it cheaper?',
            phoneticGuide: 'nung pyen-EE dyen mah',
            toneNote: '"neng" rising, "pian" rising, "yi" rising, "dian" falls-rises',
            imageQuery: 'bargaining negotiating market',
          },
        ],
        phrase: {
          chinese: '这个多少钱？太贵了！能便宜点吗？',
          pinyin: 'Zhège duōshao qián? Tài guì le! Néng piányí diǎn ma?',
          meaning: 'How much is this? Too expensive! Can you lower the price?',
          breakdown: [
            { chinese: '这个', pinyin: 'zhège', meaning: 'this one' },
            { chinese: '多少钱', pinyin: 'duōshao qián', meaning: 'how much?' },
            { chinese: '太贵了', pinyin: 'tài guì le', meaning: 'too expensive' },
            { chinese: '能便宜点吗', pinyin: 'néng piányí diǎn ma', meaning: 'can you lower the price?' },
          ],
        },
      },
      {
        id: 'travel-shopping-2',
        title: 'Clothes & Sizes',
        scenarioDescription: 'You want to try on a jacket in a clothing shop',
        conversationContext:
          'You are a shop assistant in a clothing store in China. The learner wants to try something on and is looking for the right size. Help them ask the right questions.',
        words: [
          {
            character: '大号',
            pinyin: 'dà hào',
            meaning: 'Large size (L)',
            phoneticGuide: 'dah HOW',
            toneNote: '"da" falls, "hao" falls',
            imageQuery: 'large size clothing label',
          },
          {
            character: '小号',
            pinyin: 'xiǎo hào',
            meaning: 'Small size (S)',
            phoneticGuide: 'shyow HOW',
            toneNote: '"xiao" falls-rises, "hao" falls',
            imageQuery: 'small size clothing tag',
          },
          {
            character: '试穿',
            pinyin: 'shì chuān',
            meaning: 'Try on',
            phoneticGuide: 'shrr CHWAHN',
            toneNote: '"shi" falls, "chuan" flat',
            imageQuery: 'fitting room try on clothes',
          },
        ],
        phrase: {
          chinese: '我可以试穿吗？有没有大号的？',
          pinyin: 'Wǒ kěyǐ shì chuān ma? Yǒu méiyǒu dà hào de?',
          meaning: 'Can I try it on? Do you have a large?',
          breakdown: [
            { chinese: '我可以', pinyin: 'wǒ kěyǐ', meaning: 'can I' },
            { chinese: '试穿', pinyin: 'shì chuān', meaning: 'try on' },
            { chinese: '有没有', pinyin: 'yǒu méiyǒu', meaning: 'do you have / is there' },
            { chinese: '大号的', pinyin: 'dà hào de', meaning: 'a large one' },
          ],
        },
      },
      {
        id: 'travel-shopping-3',
        title: 'Completing a Purchase',
        scenarioDescription: 'You have chosen what to buy and need to pay and get a receipt',
        conversationContext:
          'You are a cashier at a shop in China. The learner wants to buy an item, asks for a receipt, and may want to know if you accept WeChat Pay.',
        words: [
          {
            character: '买',
            pinyin: 'mǎi',
            meaning: 'Buy',
            phoneticGuide: 'my',
            toneNote: 'falls then rises',
            imageQuery: 'buying shopping purchase',
          },
          {
            character: '收据',
            pinyin: 'shōujù',
            meaning: 'Receipt',
            phoneticGuide: 'shoh JEW',
            toneNote: '"shou" flat, "ju" falls',
            imageQuery: 'receipt paper transaction',
          },
          {
            character: '微信支付',
            pinyin: 'Wēixìn zhīfù',
            meaning: 'WeChat Pay',
            phoneticGuide: 'way-SHIN jrr-FOO',
            toneNote: '"wei" flat, "xin" falls, "zhi" flat, "fu" falls',
            imageQuery: 'wechat pay mobile payment qr code',
          },
        ],
        phrase: {
          chinese: '我买这个。可以用微信支付吗？请给我收据。',
          pinyin: 'Wǒ mǎi zhège. Kěyǐ yòng Wēixìn zhīfù ma? Qǐng gěi wǒ shōujù.',
          meaning: "I'll buy this. Can I use WeChat Pay? Please give me a receipt.",
          breakdown: [
            { chinese: '我买这个', pinyin: 'wǒ mǎi zhège', meaning: "I'll buy this" },
            { chinese: '可以用', pinyin: 'kěyǐ yòng', meaning: 'can I use' },
            { chinese: '微信支付', pinyin: 'Wēixìn zhīfù', meaning: 'WeChat Pay' },
            { chinese: '请给我收据', pinyin: 'qǐng gěi wǒ shōujù', meaning: 'please give me a receipt' },
          ],
        },
      },
    ],
  },

  {
    id: 'travel-hotel',
    level: 'travel',
    title: 'At the Hotel',
    description: 'Check in, make requests, and sort out your room',
    imageQuery: 'hotel lobby china luxury',
    clusters: [
      {
        id: 'travel-hotel-1',
        title: 'Checking In',
        scenarioDescription: 'You arrive at your hotel and need to check in at the front desk',
        conversationContext:
          'You are a hotel receptionist in China. The learner has a reservation and needs to check in. Ask for their name and passport and hand over the room key.',
        words: [
          {
            character: '预订',
            pinyin: 'yùdìng',
            meaning: 'Reservation / booking',
            phoneticGuide: 'yew DING',
            toneNote: '"yu" falls, "ding" falls',
            imageQuery: 'hotel reservation booking confirmation',
          },
          {
            character: '护照',
            pinyin: 'hùzhào',
            meaning: 'Passport',
            phoneticGuide: 'hoo JHAOW',
            toneNote: '"hu" falls, "zhao" falls',
            imageQuery: 'passport travel document',
          },
          {
            character: '房间',
            pinyin: 'fángjiān',
            meaning: 'Room',
            phoneticGuide: 'fahng JYEN',
            toneNote: '"fang" rising, "jian" flat',
            imageQuery: 'hotel room bed interior',
          },
        ],
        phrase: {
          chinese: '我有预订，我叫___。这是我的护照。',
          pinyin: 'Wǒ yǒu yùdìng, wǒ jiào ___. Zhè shì wǒ de hùzhào.',
          meaning: 'I have a reservation, my name is ___. Here is my passport.',
          breakdown: [
            { chinese: '我有预订', pinyin: 'wǒ yǒu yùdìng', meaning: 'I have a reservation' },
            { chinese: '我叫', pinyin: 'wǒ jiào', meaning: 'my name is' },
            { chinese: '这是我的', pinyin: 'zhè shì wǒ de', meaning: 'here is my' },
            { chinese: '护照', pinyin: 'hùzhào', meaning: 'passport' },
          ],
        },
      },
      {
        id: 'travel-hotel-2',
        title: 'Room Requests',
        scenarioDescription: 'Something in your room is not working and you call reception',
        conversationContext:
          'You are a hotel receptionist. The learner is calling from their room with a problem — the air conditioning is broken and they need extra towels. Help them make their request.',
        words: [
          {
            character: '毛巾',
            pinyin: 'máojīn',
            meaning: 'Towel',
            phoneticGuide: 'mow JIN',
            toneNote: '"mao" rising, "jin" flat',
            imageQuery: 'towel bathroom hotel white',
          },
          {
            character: '空调',
            pinyin: 'kōngtiáo',
            meaning: 'Air conditioning',
            phoneticGuide: 'kong TYOW',
            toneNote: '"kong" flat, "tiao" rising',
            imageQuery: 'air conditioning unit cool',
          },
          {
            character: '坏了',
            pinyin: 'huài le',
            meaning: 'Broken / not working',
            phoneticGuide: 'hwai luh',
            toneNote: '"huai" falls, "le" neutral',
            imageQuery: 'broken device problem repair',
          },
        ],
        phrase: {
          chinese: '空调坏了，请送两条毛巾来。',
          pinyin: 'Kōngtiáo huài le, qǐng sòng liǎng tiáo máojīn lái.',
          meaning: 'The air conditioning is broken, please send two towels.',
          breakdown: [
            { chinese: '空调坏了', pinyin: 'kōngtiáo huài le', meaning: 'AC is broken' },
            { chinese: '请送', pinyin: 'qǐng sòng', meaning: 'please send' },
            { chinese: '两条', pinyin: 'liǎng tiáo', meaning: 'two (long/thin items)' },
            { chinese: '毛巾', pinyin: 'máojīn', meaning: 'towels' },
          ],
        },
      },
    ],
  },

  {
    id: 'travel-sights',
    level: 'travel',
    title: 'Sightseeing',
    description: 'Visit attractions, take photos, and get recommendations',
    imageQuery: 'china tourist sightseeing attraction',
    clusters: [
      {
        id: 'travel-sights-1',
        title: 'Visiting Attractions',
        scenarioDescription: 'You arrive at a museum and want to buy a ticket and take photos',
        conversationContext:
          'You are a ticket booth attendant at a popular tourist attraction in China. The learner wants to buy a ticket and asks about photography rules.',
        words: [
          {
            character: '门票',
            pinyin: 'ménpiào',
            meaning: 'Entry ticket',
            phoneticGuide: 'mun PYOW',
            toneNote: '"men" rising, "piao" falls',
            imageQuery: 'museum ticket entrance admission',
          },
          {
            character: '开放时间',
            pinyin: 'kāifàng shíjiān',
            meaning: 'Opening hours',
            phoneticGuide: 'kai-FAHNG shrr-JYEN',
            toneNote: '"kai" flat, "fang" falls, "shi" rising, "jian" flat',
            imageQuery: 'opening hours sign schedule',
          },
          {
            character: '照相',
            pinyin: 'zhào xiàng',
            meaning: 'Take a photo',
            phoneticGuide: 'jow SHYANG',
            toneNote: '"zhao" falls, "xiang" falls',
            imageQuery: 'taking photo camera tourist',
          },
        ],
        phrase: {
          chinese: '门票多少钱？我可以在这里照相吗？',
          pinyin: 'Ménpiào duōshao qián? Wǒ kěyǐ zài zhèlǐ zhào xiàng ma?',
          meaning: 'How much is the entry ticket? Can I take photos here?',
          breakdown: [
            { chinese: '门票', pinyin: 'ménpiào', meaning: 'entry ticket' },
            { chinese: '多少钱', pinyin: 'duōshao qián', meaning: 'how much?' },
            { chinese: '我可以', pinyin: 'wǒ kěyǐ', meaning: 'can I' },
            { chinese: '在这里', pinyin: 'zài zhèlǐ', meaning: 'here' },
            { chinese: '照相吗', pinyin: 'zhào xiàng ma', meaning: 'take photos?' },
          ],
        },
      },
      {
        id: 'travel-sights-2',
        title: 'Getting Recommendations',
        scenarioDescription: 'You ask a local to suggest something fun to do nearby',
        conversationContext:
          'You are a friendly local in a Chinese city. A tourist is asking for sightseeing recommendations. Suggest some places and tell them what makes each one special.',
        words: [
          {
            character: '好玩',
            pinyin: 'hǎo wán',
            meaning: 'Fun / enjoyable',
            phoneticGuide: 'how WAHN',
            toneNote: '"hao" falls-rises, "wan" rising',
            imageQuery: 'fun activity leisure enjoyment',
          },
          {
            character: '推荐',
            pinyin: 'tuījiàn',
            meaning: 'Recommend',
            phoneticGuide: 'tway JYEN',
            toneNote: '"tui" flat, "jian" falls',
            imageQuery: 'recommendation pointing suggest',
          },
          {
            character: '值得一去',
            pinyin: 'zhídé yī qù',
            meaning: 'Worth visiting',
            phoneticGuide: 'jrr-DUH ee CHEW',
            toneNote: '"zhi" rising, "de" rising, "yi" flat, "qu" falls',
            imageQuery: 'worth visiting destination travel',
          },
        ],
        phrase: {
          chinese: '你有什么推荐吗？附近有好玩的地方吗？',
          pinyin: 'Nǐ yǒu shénme tuījiàn ma? Fùjìn yǒu hǎo wán de dìfāng ma?',
          meaning: 'Do you have any recommendations? Are there fun places nearby?',
          breakdown: [
            { chinese: '你有什么推荐', pinyin: 'nǐ yǒu shénme tuījiàn', meaning: 'any recommendations?' },
            { chinese: '附近', pinyin: 'fùjìn', meaning: 'nearby' },
            { chinese: '好玩的地方', pinyin: 'hǎo wán de dìfāng', meaning: 'fun places' },
          ],
        },
      },
    ],
  },

  // ─── ADVANCED ─────────────────────────────────────────────────────────────
  {
    id: 'advanced-plans',
    level: 'advanced',
    title: 'Making Plans',
    description: 'Suggest activities and arrange meetings',
    imageQuery: 'friends planning coffee china',
    clusters: [
      {
        id: 'advanced-plans-1',
        title: 'Are You Free?',
        scenarioDescription: 'You want to invite a friend to do something together',
        conversationContext:
          'You are a friend of the learner in China. They want to make plans with you. Ask about their schedule and suggest activities to do together.',
        words: [
          {
            character: '明天',
            pinyin: 'míngtiān',
            meaning: 'Tomorrow',
            phoneticGuide: 'ming TYEN',
            toneNote: '"ming" rising, "tian" flat',
            imageQuery: 'tomorrow calendar planning',
          },
          {
            character: '有空吗',
            pinyin: 'yǒu kòng ma',
            meaning: 'Are you free?',
            phoneticGuide: 'yo KOHNG mah',
            toneNote: '"you" falls-rises, "kong" falls, "ma" neutral',
            imageQuery: 'calendar free time availability',
          },
          {
            character: '一起',
            pinyin: 'yīqǐ',
            meaning: 'Together',
            phoneticGuide: 'ee CHEE',
            toneNote: '"yi" flat, "qi" falls-rises',
            imageQuery: 'friends together group',
          },
        ],
        phrase: {
          chinese: '你明天有空吗？我们一起去吃饭吧！',
          pinyin: 'Nǐ míngtiān yǒu kòng ma? Wǒmen yīqǐ qù chīfàn ba!',
          meaning: "Are you free tomorrow? Let's go eat together!",
          breakdown: [
            { chinese: '你', pinyin: 'nǐ', meaning: 'you' },
            { chinese: '明天', pinyin: 'míngtiān', meaning: 'tomorrow' },
            { chinese: '有空吗', pinyin: 'yǒu kòng ma', meaning: 'are you free?' },
            { chinese: '我们', pinyin: 'wǒmen', meaning: 'we / us' },
            { chinese: '一起', pinyin: 'yīqǐ', meaning: 'together' },
            { chinese: '去吃饭', pinyin: 'qù chīfàn', meaning: 'go eat' },
          ],
        },
      },
      {
        id: 'advanced-plans-2',
        title: 'Setting Up a Meeting',
        scenarioDescription: 'You need to arrange a specific time to meet a colleague',
        conversationContext:
          'You are a work colleague of the learner. You need to schedule a meeting for next week. Discuss availability and agree on a time and place.',
        words: [
          {
            character: '约',
            pinyin: 'yuē',
            meaning: 'Arrange / make an appointment',
            phoneticGuide: 'yway',
            toneNote: 'flat high tone',
            imageQuery: 'calendar appointment schedule meeting',
          },
          {
            character: '见面',
            pinyin: 'jiàn miàn',
            meaning: 'Meet up / meet in person',
            phoneticGuide: 'jyen MYEN',
            toneNote: '"jian" falls, "mian" falls',
            imageQuery: 'meeting people handshake office',
          },
          {
            character: '什么时候',
            pinyin: 'shénme shíhou',
            meaning: 'When / what time',
            phoneticGuide: 'shen-muh SHRR-hoh',
            toneNote: '"shen" rising, "me" neutral, "shi" rising, "hou" neutral',
            imageQuery: 'when time question clock',
          },
        ],
        phrase: {
          chinese: '我们什么时候见面？明天下午两点怎么样？',
          pinyin: 'Wǒmen shénme shíhou jiàn miàn? Míngtiān xiàwǔ liǎng diǎn zěnmeyàng?',
          meaning: 'When should we meet? How about 2pm tomorrow afternoon?',
          breakdown: [
            { chinese: '什么时候', pinyin: 'shénme shíhou', meaning: 'when' },
            { chinese: '见面', pinyin: 'jiàn miàn', meaning: 'meet up' },
            { chinese: '明天下午', pinyin: 'míngtiān xiàwǔ', meaning: 'tomorrow afternoon' },
            { chinese: '两点', pinyin: 'liǎng diǎn', meaning: "2 o'clock" },
            { chinese: '怎么样', pinyin: 'zěnmeyàng', meaning: 'how about it?' },
          ],
        },
      },
    ],
  },

  {
    id: 'advanced-feelings',
    level: 'advanced',
    title: 'Feelings & Opinions',
    description: 'Express how you feel and share what you think',
    imageQuery: 'emotions expression feelings',
    clusters: [
      {
        id: 'advanced-feelings-1',
        title: 'How Do You Feel?',
        scenarioDescription: 'A friend is checking in on how your day went',
        conversationContext:
          'You are a caring friend checking in on the learner after a long day. Ask how they feel and share your own feelings too.',
        words: [
          {
            character: '我觉得',
            pinyin: 'wǒ juéde',
            meaning: 'I feel / I think',
            phoneticGuide: 'waw JWAY-duh',
            toneNote: '"wo" falls-rises, "jue" rising, "de" neutral',
            imageQuery: 'thinking feeling reflection',
          },
          {
            character: '累',
            pinyin: 'lèi',
            meaning: 'Tired',
            phoneticGuide: 'lay',
            toneNote: 'falls sharply',
            imageQuery: 'tired exhausted person',
          },
          {
            character: '开心',
            pinyin: 'kāixīn',
            meaning: 'Happy',
            phoneticGuide: 'kai SHIN',
            toneNote: '"kai" flat, "xin" flat',
            imageQuery: 'happy smiling person',
          },
        ],
        phrase: {
          chinese: '我今天很累，但是很开心。',
          pinyin: 'Wǒ jīntiān hěn lèi, dànshì hěn kāixīn.',
          meaning: 'I am very tired today, but very happy.',
          breakdown: [
            { chinese: '我今天', pinyin: 'wǒ jīntiān', meaning: 'I today' },
            { chinese: '很累', pinyin: 'hěn lèi', meaning: 'very tired' },
            { chinese: '但是', pinyin: 'dànshì', meaning: 'but' },
            { chinese: '很开心', pinyin: 'hěn kāixīn', meaning: 'very happy' },
          ],
        },
      },
      {
        id: 'advanced-feelings-2',
        title: 'Likes & Dislikes',
        scenarioDescription: 'Chatting with a friend about personal interests',
        conversationContext:
          'You are a Chinese friend getting to know the learner better. Ask them what they like and share your own interests. Keep it natural and friendly.',
        words: [
          {
            character: '喜欢',
            pinyin: 'xǐhuān',
            meaning: 'Like / love',
            phoneticGuide: 'shee HWAHN',
            toneNote: '"xi" falls-rises, "huan" flat',
            imageQuery: 'like heart love favourite',
          },
          {
            character: '不喜欢',
            pinyin: 'bù xǐhuān',
            meaning: "Don't like",
            phoneticGuide: 'boo shee HWAHN',
            toneNote: '"bu" falls, "xi" falls-rises, "huan" flat',
            imageQuery: 'dislike thumbs down',
          },
          {
            character: '有意思',
            pinyin: 'yǒu yìsi',
            meaning: 'Interesting',
            phoneticGuide: 'yo EE-suh',
            toneNote: '"you" falls-rises, "yi" falls, "si" neutral',
            imageQuery: 'interesting curious discovery',
          },
        ],
        phrase: {
          chinese: '你喜欢什么？我很喜欢中国文化，非常有意思。',
          pinyin: 'Nǐ xǐhuān shénme? Wǒ hěn xǐhuān Zhōngguó wénhuà, fēicháng yǒu yìsi.',
          meaning: "What do you like? I really like Chinese culture, it's very interesting.",
          breakdown: [
            { chinese: '你喜欢什么', pinyin: 'nǐ xǐhuān shénme', meaning: 'what do you like?' },
            { chinese: '我很喜欢', pinyin: 'wǒ hěn xǐhuān', meaning: 'I really like' },
            { chinese: '中国文化', pinyin: 'Zhōngguó wénhuà', meaning: 'Chinese culture' },
            { chinese: '非常有意思', pinyin: 'fēicháng yǒu yìsi', meaning: 'very interesting' },
          ],
        },
      },
      {
        id: 'advanced-feelings-3',
        title: 'Sharing Opinions',
        scenarioDescription: 'Discussing a topic and giving your point of view',
        conversationContext:
          'You are a colleague of the learner having a casual discussion. Share your opinion on a topic and ask what the learner thinks. Agree or politely disagree.',
        words: [
          {
            character: '我认为',
            pinyin: 'wǒ rènwéi',
            meaning: 'I think / I believe',
            phoneticGuide: 'waw run-WAY',
            toneNote: '"ren" falls, "wei" rising',
            imageQuery: 'thinking opinion viewpoint',
          },
          {
            character: '同意',
            pinyin: 'tóngyì',
            meaning: 'Agree',
            phoneticGuide: 'tong EE',
            toneNote: '"tong" rising, "yi" falls',
            imageQuery: 'agree nod thumbs up',
          },
          {
            character: '不一定',
            pinyin: 'bù yīdìng',
            meaning: 'Not necessarily',
            phoneticGuide: 'boo ee DING',
            toneNote: '"bu" falls, "yi" flat, "ding" falls',
            imageQuery: 'unsure hesitate maybe',
          },
        ],
        phrase: {
          chinese: '我认为这个想法很好，你同意吗？',
          pinyin: 'Wǒ rènwéi zhège xiǎngfǎ hěn hǎo, nǐ tóngyì ma?',
          meaning: 'I think this idea is very good, do you agree?',
          breakdown: [
            { chinese: '我认为', pinyin: 'wǒ rènwéi', meaning: 'I think' },
            { chinese: '这个想法', pinyin: 'zhège xiǎngfǎ', meaning: 'this idea' },
            { chinese: '很好', pinyin: 'hěn hǎo', meaning: 'very good' },
            { chinese: '你同意吗', pinyin: 'nǐ tóngyì ma', meaning: 'do you agree?' },
          ],
        },
      },
    ],
  },

  {
    id: 'advanced-work',
    level: 'advanced',
    title: 'Work & Study',
    description: 'Talk about your job, study Chinese, and handle digital life',
    imageQuery: 'office work business china professional',
    clusters: [
      {
        id: 'advanced-work-1',
        title: 'At the Office',
        scenarioDescription: 'You are discussing a project with a Chinese colleague',
        conversationContext:
          'You are a Chinese colleague at work. Discuss an upcoming meeting and a report that needs to be finished. Keep the tone professional but friendly.',
        words: [
          {
            character: '同事',
            pinyin: 'tóngshì',
            meaning: 'Colleague',
            phoneticGuide: 'tong SHRR',
            toneNote: '"tong" rising, "shi" falls',
            imageQuery: 'colleagues office team work',
          },
          {
            character: '会议',
            pinyin: 'huìyì',
            meaning: 'Meeting',
            phoneticGuide: 'hway EE',
            toneNote: '"hui" falls, "yi" falls',
            imageQuery: 'business meeting conference room',
          },
          {
            character: '报告',
            pinyin: 'bàogào',
            meaning: 'Report',
            phoneticGuide: 'bow GOW',
            toneNote: '"bao" falls, "gao" falls',
            imageQuery: 'report document presentation',
          },
        ],
        phrase: {
          chinese: '我们下午有会议，报告准备好了吗？',
          pinyin: 'Wǒmen xiàwǔ yǒu huìyì, bàogào zhǔnbèi hǎo le ma?',
          meaning: 'We have a meeting this afternoon, is the report ready?',
          breakdown: [
            { chinese: '下午', pinyin: 'xiàwǔ', meaning: 'afternoon' },
            { chinese: '有会议', pinyin: 'yǒu huìyì', meaning: 'have a meeting' },
            { chinese: '报告', pinyin: 'bàogào', meaning: 'report' },
            { chinese: '准备好了吗', pinyin: 'zhǔnbèi hǎo le ma', meaning: 'ready?' },
          ],
        },
      },
      {
        id: 'advanced-work-2',
        title: 'Studying Chinese',
        scenarioDescription: 'Checking in with your Chinese tutor on your progress',
        conversationContext:
          'You are a Chinese language tutor. The learner wants to know how their Mandarin is coming along. Encourage them and give constructive feedback.',
        words: [
          {
            character: '学习',
            pinyin: 'xuéxí',
            meaning: 'Study / learn',
            phoneticGuide: 'shway SHEE',
            toneNote: '"xue" rising, "xi" rising',
            imageQuery: 'studying books learning education',
          },
          {
            character: '练习',
            pinyin: 'liànxí',
            meaning: 'Practise',
            phoneticGuide: 'lyen SHEE',
            toneNote: '"lian" falls, "xi" rising',
            imageQuery: 'practice repetition skill',
          },
          {
            character: '进步',
            pinyin: 'jìnbù',
            meaning: 'Progress / improvement',
            phoneticGuide: 'jin BOO',
            toneNote: '"jin" falls, "bu" falls',
            imageQuery: 'progress improvement growth chart',
          },
        ],
        phrase: {
          chinese: '我每天练习汉语，我的汉语有进步吗？',
          pinyin: 'Wǒ měitiān liànxí Hànyǔ, wǒ de Hànyǔ yǒu jìnbù ma?',
          meaning: 'I practise Chinese every day, is my Chinese improving?',
          breakdown: [
            { chinese: '每天', pinyin: 'měitiān', meaning: 'every day' },
            { chinese: '练习汉语', pinyin: 'liànxí Hànyǔ', meaning: 'practise Chinese' },
            { chinese: '有进步吗', pinyin: 'yǒu jìnbù ma', meaning: 'is there improvement?' },
          ],
        },
      },
      {
        id: 'advanced-work-3',
        title: 'Digital & Mobile Life',
        scenarioDescription: 'You need WiFi and want to know how to pay with your phone',
        conversationContext:
          'You are a café owner in China. A customer wants the WiFi password and asks if you accept mobile payment. Help them with these common modern requests.',
        words: [
          {
            character: '手机',
            pinyin: 'shǒujī',
            meaning: 'Mobile phone',
            phoneticGuide: 'shoh JEE',
            toneNote: '"shou" falls-rises, "ji" flat',
            imageQuery: 'mobile phone smartphone screen',
          },
          {
            character: '网络',
            pinyin: 'wǎngluò',
            meaning: 'Internet / network',
            phoneticGuide: 'wahng LWAW',
            toneNote: '"wang" falls-rises, "luo" falls',
            imageQuery: 'wifi internet connection network',
          },
          {
            character: '扫码',
            pinyin: 'sǎo mǎ',
            meaning: 'Scan a QR code',
            phoneticGuide: 'sow MAH',
            toneNote: '"sao" falls-rises, "ma" falls-rises',
            imageQuery: 'qr code scan mobile payment',
          },
        ],
        phrase: {
          chinese: '这里有没有网络？我可以扫码付款吗？',
          pinyin: 'Zhèlǐ yǒu méiyǒu wǎngluò? Wǒ kěyǐ sǎo mǎ fùkuǎn ma?',
          meaning: 'Is there internet here? Can I pay by scanning a QR code?',
          breakdown: [
            { chinese: '这里', pinyin: 'zhèlǐ', meaning: 'here' },
            { chinese: '有没有网络', pinyin: 'yǒu méiyǒu wǎngluò', meaning: 'is there internet?' },
            { chinese: '扫码', pinyin: 'sǎo mǎ', meaning: 'scan QR code' },
            { chinese: '付款', pinyin: 'fùkuǎn', meaning: 'make payment' },
          ],
        },
      },
    ],
  },

  {
    id: 'advanced-weather',
    level: 'advanced',
    title: 'Weather & Seasons',
    description: 'Talk about the weather and climate',
    imageQuery: 'weather seasons china nature',
    clusters: [
      {
        id: 'advanced-weather-1',
        title: "What's the Weather Like?",
        scenarioDescription: 'Chatting with a colleague about the weather forecast',
        conversationContext:
          "You are a colleague of the learner making small talk. Discuss today's weather and what the forecast says for the rest of the week.",
        words: [
          {
            character: '天气',
            pinyin: 'tiānqì',
            meaning: 'Weather',
            phoneticGuide: 'tyen CHEE',
            toneNote: '"tian" flat, "qi" falls',
            imageQuery: 'weather forecast sky clouds',
          },
          {
            character: '下雨',
            pinyin: 'xià yǔ',
            meaning: 'Raining / to rain',
            phoneticGuide: 'shyah YEW',
            toneNote: '"xia" falls, "yu" falls-rises',
            imageQuery: 'rain umbrella wet weather',
          },
          {
            character: '刮风',
            pinyin: 'guā fēng',
            meaning: 'Windy / blowing wind',
            phoneticGuide: 'gwah FUNG',
            toneNote: '"gua" flat, "feng" flat',
            imageQuery: 'windy trees blowing',
          },
        ],
        phrase: {
          chinese: '今天天气怎么样？天气预报说明天会下雨。',
          pinyin: 'Jīntiān tiānqì zěnmeyàng? Tiānqì yùbào shuō míngtiān huì xià yǔ.',
          meaning: "What's the weather like today? The forecast says it will rain tomorrow.",
          breakdown: [
            { chinese: '今天天气', pinyin: 'jīntiān tiānqì', meaning: "today's weather" },
            { chinese: '怎么样', pinyin: 'zěnmeyàng', meaning: 'how is it?' },
            { chinese: '天气预报', pinyin: 'tiānqì yùbào', meaning: 'weather forecast' },
            { chinese: '会下雨', pinyin: 'huì xià yǔ', meaning: 'will rain' },
          ],
        },
      },
      {
        id: 'advanced-weather-2',
        title: 'Seasons & Temperature',
        scenarioDescription: 'A friend asks what the seasons are like in your city',
        conversationContext:
          "You are a Chinese friend curious about weather in the learner's home country. Compare it to China's climate. Discuss temperatures and which season you prefer.",
        words: [
          {
            character: '热',
            pinyin: 'rè',
            meaning: 'Hot',
            phoneticGuide: 'ruh',
            toneNote: 'falls sharply',
            imageQuery: 'hot summer sun heat',
          },
          {
            character: '冷',
            pinyin: 'lěng',
            meaning: 'Cold',
            phoneticGuide: 'lung',
            toneNote: 'falls then rises',
            imageQuery: 'cold winter snow ice',
          },
          {
            character: '季节',
            pinyin: 'jìjié',
            meaning: 'Season',
            phoneticGuide: 'jee JYEH',
            toneNote: '"ji" falls, "jie" rising',
            imageQuery: 'four seasons nature change',
          },
        ],
        phrase: {
          chinese: '北京的冬天很冷，夏天非常热。你最喜欢哪个季节？',
          pinyin: 'Běijīng de dōngtiān hěn lěng, xiàtiān fēicháng rè. Nǐ zuì xǐhuān nǎ gè jìjié?',
          meaning: "Beijing's winters are very cold and summers are extremely hot. What season do you like most?",
          breakdown: [
            { chinese: '冬天', pinyin: 'dōngtiān', meaning: 'winter' },
            { chinese: '很冷', pinyin: 'hěn lěng', meaning: 'very cold' },
            { chinese: '夏天', pinyin: 'xiàtiān', meaning: 'summer' },
            { chinese: '非常热', pinyin: 'fēicháng rè', meaning: 'extremely hot' },
            { chinese: '哪个季节', pinyin: 'nǎ gè jìjié', meaning: 'which season' },
          ],
        },
      },
    ],
  },

  {
    id: 'advanced-health',
    level: 'advanced',
    title: 'Health & Wellbeing',
    description: 'Describe symptoms and find a pharmacy',
    imageQuery: 'health medical pharmacy china',
    clusters: [
      {
        id: 'advanced-health-1',
        title: 'Feeling Unwell',
        scenarioDescription: 'You are not feeling well and a friend is asking what is wrong',
        conversationContext:
          'You are a concerned friend. The learner is not feeling well. Ask them what is wrong and whether they need to see a doctor or just rest.',
        words: [
          {
            character: '头疼',
            pinyin: 'tóuténg',
            meaning: 'Headache',
            phoneticGuide: 'toh TUNG',
            toneNote: '"tou" rising, "teng" rising',
            imageQuery: 'headache pain head person',
          },
          {
            character: '发烧',
            pinyin: 'fāshāo',
            meaning: 'Fever',
            phoneticGuide: 'fah SHOW',
            toneNote: '"fa" flat, "shao" flat',
            imageQuery: 'fever thermometer sick temperature',
          },
          {
            character: '不舒服',
            pinyin: 'bù shūfu',
            meaning: 'Unwell / uncomfortable',
            phoneticGuide: 'boo SHOO-foo',
            toneNote: '"bu" falls, "shu" flat, "fu" neutral',
            imageQuery: 'unwell sick discomfort person',
          },
        ],
        phrase: {
          chinese: '我头疼，我觉得我发烧了，很不舒服。',
          pinyin: 'Wǒ tóuténg, wǒ juéde wǒ fāshāo le, hěn bù shūfu.',
          meaning: 'I have a headache, I think I have a fever, I feel really unwell.',
          breakdown: [
            { chinese: '我头疼', pinyin: 'wǒ tóuténg', meaning: 'I have a headache' },
            { chinese: '我觉得', pinyin: 'wǒ juéde', meaning: 'I think / I feel' },
            { chinese: '发烧了', pinyin: 'fāshāo le', meaning: 'have a fever' },
            { chinese: '很不舒服', pinyin: 'hěn bù shūfu', meaning: 'feel very unwell' },
          ],
        },
      },
      {
        id: 'advanced-health-2',
        title: 'At the Pharmacy',
        scenarioDescription: 'You need to find a pharmacy and buy medicine for a headache',
        conversationContext:
          'You are a pharmacist in China. The learner comes in feeling unwell. Ask them about their symptoms and recommend the right medicine.',
        words: [
          {
            character: '药',
            pinyin: 'yào',
            meaning: 'Medicine',
            phoneticGuide: 'yow',
            toneNote: 'falls sharply',
            imageQuery: 'medicine pills pharmacy tablets',
          },
          {
            character: '药店',
            pinyin: 'yàodiàn',
            meaning: 'Pharmacy / chemist',
            phoneticGuide: 'yow DYEN',
            toneNote: '"yao" falls, "dian" falls',
            imageQuery: 'pharmacy drugstore sign green cross',
          },
          {
            character: '吃药',
            pinyin: 'chī yào',
            meaning: 'Take medicine',
            phoneticGuide: 'chrr YOW',
            toneNote: '"chi" flat, "yao" falls',
            imageQuery: 'taking medicine tablet water glass',
          },
        ],
        phrase: {
          chinese: '请问附近有药店吗？我需要头疼药。',
          pinyin: 'Qǐngwèn fùjìn yǒu yàodiàn ma? Wǒ xūyào tóuténg yào.',
          meaning: 'Excuse me, is there a pharmacy nearby? I need headache medicine.',
          breakdown: [
            { chinese: '附近有药店吗', pinyin: 'fùjìn yǒu yàodiàn ma', meaning: 'pharmacy nearby?' },
            { chinese: '我需要', pinyin: 'wǒ xūyào', meaning: 'I need' },
            { chinese: '头疼药', pinyin: 'tóuténg yào', meaning: 'headache medicine' },
          ],
        },
      },
    ],
  },
]

export function getUnitsByLevel(level: string): Unit[] {
  return units.filter((u) => u.level === level)
}

export function getUnit(unitId: string): Unit | undefined {
  return units.find((u) => u.id === unitId)
}
